workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean iOS
        script: |
          flutter clean
          flutter pub get
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Build iOS Simulator
        script: flutter build ios --simulator
      - name: Zip App
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
